name: Verify Icons

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify icon references
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          ./scripts/verify-icons.ps1

